### ISSUE TITLE
Fix Required : Accessibility

### ISSUE THREAD

**Issue by lukejones** [lukejones/designchallenge#12]
I like the color palette right now, but it's not accessible. Work on developing a color palette that is both appealing and meets AA contrast standards.

**Comment by daviddarnes** [comment]
@lukejones I used the audit tools in Chrome to see what the colours on the current holding page do, they seem to pass (except for the footer text). Are you thinking of different colours or are you using a different tool? ![screen shot 2018-05-23 at 10 10 40](https://user-images.githubusercontent.com/1177460/40422422-2e754c22-5e87-11e8-82be-501518b2e9fd.png)

**Comment by lukejones** [comment]
@daviddarnes Aha, this is definitely more about the site that is yet to come. The colors I’m using are pretty wild. Planning on getting this sorted today.

**Comment by lukejones** [comment]
@daviddarnes Sorted:

![image](https://user-images.githubusercontent.com/508797/40433714-9bb25d28-5e7a-11e8-8d51-5c359ef12b98.png)

Also:

<img width="426" alt="image" src="https://user-images.githubusercontent.com/508797/40433687-8db2cd66-5e7a-11e8-8033-bdac63c5d493.png">
