### ISSUE TITLE
Fix HTTPS issue

### ISSUE THREAD

**Issue by lukejones** [lukejones/designchallenge#2]
Despite HTTPS working, the page does not automatically redirect to https - fix this so people using the site know everything is submitted securely.

**Comment by mikefrancis** [comment]
Hey Luke,

You should be able to do this in Settings > GitHub Pages:

<img width="706" alt="screen shot 2018-05-22 at 11 50 15" src="https://user-images.githubusercontent.com/1672610/40358386-f9e18848-5db6-11e8-9717-b58427e9a867.png">

Ignore my shitty DNS 😅

**Comment by lukejones** [comment]
@mikefrancis - It's an odd one, I have cloudflare set up (go to https://designchallenge.xyz or https://lukejones.me) and that button can’t be checked on either.

**Comment by lukejones** [comment]
In the meantime, I’ve thrown this into the `<head>`:

```
        <script type="text/javascript">
            var host = "designchallenge.xyz";
            if ((host == window.location.host) && (window.location.protocol != "https:"))
            window.location.protocol = "https";
        </script>
```

**Comment by mikefrancis** [comment]
Ah ok, maybe check this out - seems to be down to what A records you add:

https://github.community/t5/Pages/How-to-enable-https-support-on-custom-domains/td-p/6894

**Comment by lukejones** [comment]
That makes sense. Apparently I need to set up an ALIAS or an ANAME to enable that force https:// thing. That said, I _think_ because I have everything set up through CloudFlare it should be okay...
