### ISSUE TITLE
Close modal window when I click "ESC"

### ISSUE THREAD

**Issue by nk8** [lukejones/designchallenge#21]
Most designers are familiar with the power of keyboard shortcuts. Naturally, we like to hit "ESC" to close popouts / modals that we don't want to see. 

It would be great to add keyboard event listener to "close modal" when user clicks "ESC" on a modal screen.

...not a huge thing, but just wanted to add a small, but useful issue ticket.

**Comment by robb0wen** [comment]
Good call. I've added escape key handling for all modals
